using System.Globalization;
using System.Resources;

namespace TrackZ.Mobile.Features.Localization;

public sealed record MobileTextSet(
    string Language,
    string ThaiLanguage,
    string EnglishLanguage,
    string LanguageSwitchFailed,
    string CustomExerciseTitle,
    string CustomExerciseFormTitle,
    string CustomExerciseIntro,
    string ExerciseName,
    string BodyPart,
    string TrackingMode,
    string TrackingModeQuestion,
    string OptionalExerciseImage,
    string ExerciseImageOptionalHelp,
    string AddExerciseImage,
    string CaptureExerciseImage,
    string HideExerciseImages,
    string ExerciseImagePlaceholder,
    string ChooseExerciseImage,
    string ChooseFromExerciseLibrary,
    string PublishedLibraryImages,
    string ExerciseImageRetentionHelp,
    string SaveExercise,
    string UnsupportedExerciseImage,
    string ImageNotImported,
    string ExerciseNotSaved,
    string ExerciseSaveFailedFormat,
    string Okay,
    string BodyPartChest,
    string BodyPartBack,
    string BodyPartShoulders,
    string BodyPartArms,
    string BodyPartLegs,
    string BodyPartCore,
    string TrackingWeighted,
    string TrackingAssisted,
    string TrackingBodyweight,
    string ExerciseNameValidation,
    string BodyPartValidation,
    string TrackingModeValidation,
    string ImageSourceConflict,
    string LocalImageMissing,
    string SignOutTitle,
    string SignOutMessage,
    string SignOutDataTitle,
    string SignOutDataMessage,
    string SignOutUnknownTitle,
    string SignOutUnknownMessage,
    string SignOutAndDelete,
    string StaySignedIn,
    string SignOutCheckFailed,
    string SignOutFailed);

public static class MobileResources
{
    private static readonly ResourceManager Manager = new(
        $"{typeof(MobileResources).Assembly.GetName().Name}.Resources.MobileStrings",
        typeof(MobileResources).Assembly);

    public static MobileTextSet ForCulture(CultureInfo culture)
    {
        ArgumentNullException.ThrowIfNull(culture);
        return new MobileTextSet(
            Value("Language", culture),
            Value("ThaiLanguage", culture),
            Value("EnglishLanguage", culture),
            Value("LanguageSwitchFailed", culture),
            Value("CustomExerciseTitle", culture),
            Value("CustomExerciseFormTitle", culture),
            Value("CustomExerciseIntro", culture),
            Value("ExerciseName", culture),
            Value("BodyPart", culture),
            Value("TrackingMode", culture),
            Value("TrackingModeQuestion", culture),
            Value("OptionalExerciseImage", culture),
            Value("ExerciseImageOptionalHelp", culture),
            Value("AddExerciseImage", culture),
            Value("CaptureExerciseImage", culture),
            Value("HideExerciseImages", culture),
            Value("ExerciseImagePlaceholder", culture),
            Value("ChooseExerciseImage", culture),
            Value("ChooseFromExerciseLibrary", culture),
            Value("PublishedLibraryImages", culture),
            Value("ExerciseImageRetentionHelp", culture),
            Value("SaveExercise", culture),
            Value("UnsupportedExerciseImage", culture),
            Value("ImageNotImported", culture),
            Value("ExerciseNotSaved", culture),
            Value("ExerciseSaveFailedFormat", culture),
            Value("Okay", culture),
            Value("BodyPartChest", culture),
            Value("BodyPartBack", culture),
            Value("BodyPartShoulders", culture),
            Value("BodyPartArms", culture),
            Value("BodyPartLegs", culture),
            Value("BodyPartCore", culture),
            Value("TrackingWeighted", culture),
            Value("TrackingAssisted", culture),
            Value("TrackingBodyweight", culture),
            Value("ExerciseNameValidation", culture),
            Value("BodyPartValidation", culture),
            Value("TrackingModeValidation", culture),
            Value("ImageSourceConflict", culture),
            Value("LocalImageMissing", culture),
            Value("SignOutTitle", culture),
            Value("SignOutMessage", culture),
            Value("SignOutDataTitle", culture),
            Value("SignOutDataMessage", culture),
            Value("SignOutUnknownTitle", culture),
            Value("SignOutUnknownMessage", culture),
            Value("SignOutAndDelete", culture),
            Value("StaySignedIn", culture),
            Value("SignOutCheckFailed", culture),
            Value("SignOutFailed", culture));
    }

    private static string Value(string key, CultureInfo culture) =>
        Manager.GetString(key, culture)
        ?? throw new MissingManifestResourceException($"Mobile resource '{key}' is missing.");
}
