using System.Globalization;
using System.Resources;

namespace TrackZ.Mobile.Features.Workout;

public sealed record WorkoutTextSet(
    string Offline,
    string Pending,
    string Conflicted,
    string PermanentFailure,
    string Syncing,
    string Reconciling,
    string Synced,
    string InvalidWeightedSet,
    string InvalidAssistedSet,
    string InvalidBodyweightSet,
    string SaveFailed,
    string LoadFailed,
    string WorkoutTitle,
    string SetLoggerTitle,
    string Last,
    string Today,
    string MatchLast,
    string CompleteSet,
    string AddExercise,
    string StartWorkout,
    string Remove,
    string MoveUp,
    string MoveDown,
    string Weight,
    string Assistance,
    string Reps,
    string RepsFieldLabel,
    string Kilograms,
    string Pounds,
    string Bodyweight,
    string NoExercises,
    string SavedLocally,
    string ChooseExercises,
    string SearchExercises,
    string AllBodyParts,
    string All,
    string SelectedCountFormat,
    string NoMatchingExercises,
    string NoMatchingExercisesSupporting,
    string BodyPartFilterFormat,
    string CreateCustom,
    string Done,
    string ExerciseSelectionRequiredTitle,
    string ExerciseSelectionRequiredMessage,
    string Okay,
    string SignIn,
    string TryAgain,
    string BodyPartChest,
    string BodyPartBack,
    string BodyPartShoulders,
    string BodyPartArms,
    string BodyPartLegs,
    string BodyPartCore,
    string DecreaseWeight,
    string IncreaseWeight,
    string DecreaseAssistance,
    string IncreaseAssistance,
    string DecreaseReps,
    string IncreaseReps,
    string PerformanceLastFormat,
    string PerformancePrFormat,
    string Edit,
    string PendingSync,
    string WeightedPerformanceFormat,
    string AssistedPerformanceFormat,
    string BodyweightPerformanceFormat,
    string RepSingular,
    string RepPlural,
    string FinishWorkout,
    string HistoryTitle,
    string HistoryTab,
    string NoHistory,
    string Delete,
    string Undo,
    string Confirm,
    string Cancel,
    string DeleteSetTitle,
    string DeleteSetMessage,
    string DeleteWorkoutTitle,
    string DeleteWorkoutMessage,
    string HistoryEditFailed,
    string HistoryDeleteFailed,
    string UndoFailed,
    string KeepServer,
    string ApplyLocal,
    string HistoryConflictFailed,
    string UnknownExercise,
    string DeleteExerciseTitle,
    string DeleteExerciseMessage,
    string TrainTodayTitle,
    string ChooseWorkout,
    string ResumeWorkout,
    string Continue,
    string TrainTab,
    string SavedSetCountFormat,
    string ExerciseCountFormat,
    string ArtworkUnavailable,
    string RetryArtwork,
    string SelectExerciseFormat,
    string ArtworkForExerciseFormat,
    string SetCountSingularFormat,
    string SetCountPluralFormat,
    string OpenSetLoggerAccessibilityFormat,
    string SetsLoggedFormat,
    string LogNextSet,
    string SaveSet,
    string NextSetFormat,
    string SetSaved,
    string SetSavedSecondary,
    string MatchedPreviousSet,
    string MatchedPreviousSecondary,
    string PersonalRecordSaved,
    string PersonalRecordSecondary,
    string LowerAssistanceProgress,
    string NoPreviousSetsYet,
    string SaveSetNumberFormat,
    string ReadyWhenYouAre,
    string YouAreInMotion,
    string StartTraining,
    string ChooseTodaysWorkout,
    string ChooseWorkoutSupporting,
    string WorkoutInProgress,
    string ContinueWorkout,
    string ThisWeek,
    string WeekStreak,
    string LevelXpFormat,
    string TrainAgain,
    string RecentMomentum,
    string LastBestFormat,
    string HomeExerciseProgressFormat,
    string RepeatWorkoutAccessibilityFormat,
    string HomeLoadFailed,
    string HomeRepeatFailed,
    string HomeOpenWorkoutFailed,
    string HomeOpenProgressFailed,
    string HomeContextFormat,
    string LastWorkoutSetsFormat,
    string PreviousWorkoutReference,
    string HeaviestSetInRepRange,
    string LightestAssistanceInRepRange,
    string HighestRepsInRepRange,
    string LegacyWorkoutReference,
    string FinishNeedsSetsFormat,
    string DismissNotice,
    string ConflictLocalBaseFormat,
    string ConflictLocalDetailFormat,
    string ConflictServerVersionFormat,
    string ConflictServerDetailFormat,
    string ConflictExerciseSingularFormat,
    string ConflictExercisePluralFormat,
    string ConflictSetSingularFormat,
    string ConflictSetPluralFormat,
    string EffortSheetTitle,
    string EffortSetSaved,
    string EffortQuestion,
    string EffortGoodFormHelper,
    string EffortEasyOption,
    string EffortProductiveOption,
    string EffortTooHeavyOption,
    string EffortSkip,
    string EffortPainSafety,
    string EffortSaving,
    string EffortSaveFailed,
    string EffortUnavailable,
    string EffortOriginalSetSafe,
    string Retry,
    string NotNow,
    string GuidanceIncrementTitle,
    string GuidanceIncrementHelper,
    string GuidanceIncrementPlaceholder,
    string GuidanceSaveIncrement,
    string GuidanceEditIncrement,
    string GuidanceIncrementInvalid,
    string GuidanceAlmostReady,
    string GuidanceNeedAnotherReason,
    string GuidanceKeepLoadFormat,
    string GuidanceTryRepsFormat,
    string GuidanceTryWeightNextSetFormat,
    string GuidanceTryAssistanceNextSetFormat,
    string GuidanceTwoSetsReason,
    string GuidanceKeepReason,
    string GuidanceReduceReason,
    string GuidanceLessAssistanceReason,
    string GuidanceMoreAssistanceReason,
    string GuidanceBelowRangeReason,
    string GuidanceReduceDifficulty,
    string GuidanceBodyweightComplete,
    string GuidanceNoSuggestion,
    string GuidanceNoSuggestionReason,
    string GuidanceKeepCurrentLoad,
    string GuidanceHigherLoadUnavailable,
    string GuidanceKeepCurrentAssistance,
    string GuidanceLowerAssistanceUnavailable,
    string GuidanceUseWeightFormat,
    string GuidanceUseAssistanceFormat,
    string GuidanceUseRepsFormat,
    string HomeWeeklyGoalFormat,
    string HomeWeeklyStreakFormat,
    string HomeWeeklyGoalTitle,
    string HomeWeeklyGoalUnit,
    string HomeWeeklyGoalRemainingFormat,
    string HomeLatestPerformance,
    string HomeNoWorkoutHistory,
    string HomeNoWorkoutHistorySupporting,
    string HomeLatestLabel,
    string HomeBestLabel,
    string HomeViewAllData,
    string HomeWeightedValueFormat,
    string HomeAssistedValueFormat,
    string HomeBodyweightValueFormat,
    string Open,
    string DiscardWorkout,
    string DiscardWorkoutTitle,
    string DiscardWorkoutMessage,
    string DiscardWorkoutFailed,
    string ExactWeight,
    string PlateCount,
    string PlateCountHint,
    string PlateMeasurementFormat,
    string InvalidPlateCountSet,
    string LoadType,
    string StartFirstExercise,
    string LogNextWorkoutSet,
    string ProgressFormat,
    string NoSetsYet,
    string TodaySetsTitle,
    string NoSetsToday,
    string NoSetsTodaySupporting,
    string AddSetNumberFormat,
    string WeightUnitTitle,
    string DraftInputHelper);

public static class WorkoutResources
{
    private static readonly ResourceManager Manager = new(
        $"{typeof(WorkoutResources).Assembly.GetName().Name}.Resources.WorkoutStrings",
        typeof(WorkoutResources).Assembly);

    public static WorkoutTextSet English { get; } = ForCulture(CultureInfo.GetCultureInfo("en-US"));
    public static WorkoutTextSet Current => ForCulture(CultureInfo.CurrentUICulture);

    public static WorkoutTextSet ForCulture(CultureInfo culture)
    {
        ArgumentNullException.ThrowIfNull(culture);
        return new WorkoutTextSet(
            Value("Offline", culture), Value("Pending", culture), Value("Conflicted", culture), Value("PermanentFailure", culture),
            Value("Syncing", culture), Value("Reconciling", culture), Value("Synced", culture), Value("InvalidWeightedSet", culture),
            Value("InvalidAssistedSet", culture), Value("InvalidBodyweightSet", culture),
            Value("SaveFailed", culture), Value("LoadFailed", culture), Value("WorkoutTitle", culture), Value("SetLoggerTitle", culture),
            Value("Last", culture), Value("Today", culture), Value("MatchLast", culture),
            Value("CompleteSet", culture), Value("AddExercise", culture), Value("StartWorkout", culture),
            Value("Remove", culture), Value("MoveUp", culture), Value("MoveDown", culture),
            Value("Weight", culture), Value("Assistance", culture), Value("Reps", culture),
            Value("RepsFieldLabel", culture),
            Value("Kilograms", culture), Value("Pounds", culture),
            Value("Bodyweight", culture), Value("NoExercises", culture), Value("SavedLocally", culture),
            Value("ChooseExercises", culture), Value("SearchExercises", culture), Value("AllBodyParts", culture),
            Value("All", culture), Value("SelectedCountFormat", culture), Value("NoMatchingExercises", culture),
            Value("NoMatchingExercisesSupporting", culture), Value("BodyPartFilterFormat", culture),
            Value("CreateCustom", culture), Value("Done", culture),
            Value("ExerciseSelectionRequiredTitle", culture),
            Value("ExerciseSelectionRequiredMessage", culture), Value("Okay", culture),
            Value("SignIn", culture), Value("TryAgain", culture), Value("BodyPartChest", culture),
            Value("BodyPartBack", culture), Value("BodyPartShoulders", culture), Value("BodyPartArms", culture),
            Value("BodyPartLegs", culture), Value("BodyPartCore", culture),
            Value("DecreaseWeight", culture), Value("IncreaseWeight", culture),
            Value("DecreaseAssistance", culture), Value("IncreaseAssistance", culture),
            Value("DecreaseReps", culture), Value("IncreaseReps", culture),
            Value("PerformanceLastFormat", culture), Value("PerformancePrFormat", culture),
            Value("Edit", culture), Value("PendingSync", culture),
            Value("WeightedPerformanceFormat", culture), Value("AssistedPerformanceFormat", culture),
            Value("BodyweightPerformanceFormat", culture), Value("RepSingular", culture),
            Value("RepPlural", culture), Value("FinishWorkout", culture),
            Value("HistoryTitle", culture), Value("HistoryTab", culture), Value("NoHistory", culture),
            Value("Delete", culture), Value("Undo", culture), Value("Confirm", culture),
            Value("Cancel", culture), Value("DeleteSetTitle", culture),
            Value("DeleteSetMessage", culture), Value("DeleteWorkoutTitle", culture),
            Value("DeleteWorkoutMessage", culture), Value("HistoryEditFailed", culture),
            Value("HistoryDeleteFailed", culture), Value("UndoFailed", culture),
            Value("KeepServer", culture), Value("ApplyLocal", culture),
            Value("HistoryConflictFailed", culture), Value("UnknownExercise", culture),
            Value("DeleteExerciseTitle", culture), Value("DeleteExerciseMessage", culture),
            Value("TrainTodayTitle", culture), Value("ChooseWorkout", culture),
            Value("ResumeWorkout", culture), Value("Continue", culture),
            Value("TrainTab", culture), Value("SavedSetCountFormat", culture),
            Value("ExerciseCountFormat", culture), Value("ArtworkUnavailable", culture),
            Value("RetryArtwork", culture), Value("SelectExerciseFormat", culture),
            Value("ArtworkForExerciseFormat", culture),
            Value("SetCountSingularFormat", culture), Value("SetCountPluralFormat", culture),
            Value("OpenSetLoggerAccessibilityFormat", culture), Value("SetsLoggedFormat", culture),
            Value("LogNextSet", culture), Value("SaveSet", culture), Value("NextSetFormat", culture),
            Value("SetSaved", culture), Value("SetSavedSecondary", culture),
            Value("MatchedPreviousSet", culture), Value("MatchedPreviousSecondary", culture),
            Value("PersonalRecordSaved", culture), Value("PersonalRecordSecondary", culture),
            Value("LowerAssistanceProgress", culture), Value("NoPreviousSetsYet", culture),
            Value("SaveSetNumberFormat", culture), Value("ReadyWhenYouAre", culture),
            Value("YouAreInMotion", culture), Value("StartTraining", culture),
            Value("ChooseTodaysWorkout", culture), Value("ChooseWorkoutSupporting", culture),
            Value("WorkoutInProgress", culture), Value("ContinueWorkout", culture),
            Value("ThisWeek", culture), Value("WeekStreak", culture),
            Value("LevelXpFormat", culture), Value("TrainAgain", culture),
            Value("RecentMomentum", culture), Value("LastBestFormat", culture),
            Value("HomeExerciseProgressFormat", culture), Value("RepeatWorkoutAccessibilityFormat", culture),
            Value("HomeLoadFailed", culture), Value("HomeRepeatFailed", culture),
            Value("HomeOpenWorkoutFailed", culture),
            Value("HomeOpenProgressFailed", culture),
            Value("HomeContextFormat", culture),
            Value("LastWorkoutSetsFormat", culture),
            Value("PreviousWorkoutReference", culture),
            Value("HeaviestSetInRepRange", culture),
            Value("LightestAssistanceInRepRange", culture),
            Value("HighestRepsInRepRange", culture),
            Value("LegacyWorkoutReference", culture),
            Value("FinishNeedsSetsFormat", culture),
            Value("DismissNotice", culture),
            Value("ConflictLocalBaseFormat", culture),
            Value("ConflictLocalDetailFormat", culture),
            Value("ConflictServerVersionFormat", culture),
            Value("ConflictServerDetailFormat", culture),
            Value("ConflictExerciseSingularFormat", culture),
            Value("ConflictExercisePluralFormat", culture),
            Value("ConflictSetSingularFormat", culture),
            Value("ConflictSetPluralFormat", culture),
            Value("EffortSheetTitle", culture),
            Value("EffortSetSaved", culture),
            Value("EffortQuestion", culture),
            Value("EffortGoodFormHelper", culture),
            Value("EffortEasyOption", culture),
            Value("EffortProductiveOption", culture),
            Value("EffortTooHeavyOption", culture),
            Value("EffortSkip", culture),
            Value("EffortPainSafety", culture),
            Value("EffortSaving", culture),
            Value("EffortSaveFailed", culture),
            Value("EffortUnavailable", culture),
            Value("EffortOriginalSetSafe", culture),
            Value("Retry", culture),
            Value("NotNow", culture),
            Value("GuidanceIncrementTitle", culture),
            Value("GuidanceIncrementHelper", culture),
            Value("GuidanceIncrementPlaceholder", culture),
            Value("GuidanceSaveIncrement", culture),
            Value("GuidanceEditIncrement", culture),
            Value("GuidanceIncrementInvalid", culture),
            Value("GuidanceAlmostReady", culture),
            Value("GuidanceNeedAnotherReason", culture),
            Value("GuidanceKeepLoadFormat", culture),
            Value("GuidanceTryRepsFormat", culture),
            Value("GuidanceTryWeightNextSetFormat", culture),
            Value("GuidanceTryAssistanceNextSetFormat", culture),
            Value("GuidanceTwoSetsReason", culture),
            Value("GuidanceKeepReason", culture),
            Value("GuidanceReduceReason", culture),
            Value("GuidanceLessAssistanceReason", culture),
            Value("GuidanceMoreAssistanceReason", culture),
            Value("GuidanceBelowRangeReason", culture),
            Value("GuidanceReduceDifficulty", culture),
            Value("GuidanceBodyweightComplete", culture),
            Value("GuidanceNoSuggestion", culture),
            Value("GuidanceNoSuggestionReason", culture),
            Value("GuidanceKeepCurrentLoad", culture),
            Value("GuidanceHigherLoadUnavailable", culture),
            Value("GuidanceKeepCurrentAssistance", culture),
            Value("GuidanceLowerAssistanceUnavailable", culture),
            Value("GuidanceUseWeightFormat", culture),
            Value("GuidanceUseAssistanceFormat", culture),
            Value("GuidanceUseRepsFormat", culture),
            Value("HomeWeeklyGoalFormat", culture),
            Value("HomeWeeklyStreakFormat", culture),
            Value("HomeWeeklyGoalTitle", culture),
            Value("HomeWeeklyGoalUnit", culture),
            Value("HomeWeeklyGoalRemainingFormat", culture),
            Value("HomeLatestPerformance", culture),
            Value("HomeNoWorkoutHistory", culture),
            Value("HomeNoWorkoutHistorySupporting", culture),
            Value("HomeLatestLabel", culture),
            Value("HomeBestLabel", culture),
            Value("HomeViewAllData", culture),
            Value("HomeWeightedValueFormat", culture),
            Value("HomeAssistedValueFormat", culture),
            Value("HomeBodyweightValueFormat", culture),
            Value("Open", culture),
            Value("DiscardWorkout", culture),
            Value("DiscardWorkoutTitle", culture),
            Value("DiscardWorkoutMessage", culture),
            Value("DiscardWorkoutFailed", culture),
            Value("ExactWeight", culture),
            Value("PlateCount", culture),
            Value("PlateCountHint", culture),
            Value("PlateMeasurementFormat", culture),
            Value("InvalidPlateCountSet", culture),
            Value("LoadType", culture),
            Value("StartFirstExercise", culture),
            Value("LogNextWorkoutSet", culture),
            Value("ProgressFormat", culture),
            Value("NoSetsYet", culture),
            Value("TodaySetsTitle", culture),
            Value("NoSetsToday", culture),
            Value("NoSetsTodaySupporting", culture),
            Value("AddSetNumberFormat", culture),
            Value("WeightUnitTitle", culture),
            Value("DraftInputHelper", culture));
    }

    private static string Value(string key, CultureInfo culture) =>
        Manager.GetString(key, culture)
        ?? throw new MissingManifestResourceException($"Workout resource '{key}' is missing.");
}
