// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrackZ.Infrastructure.Persistence;

#nullable disable

namespace TrackZ.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260815161433_HardenWorkoutPersistence")]
    partial class HardenWorkoutPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrackZ.Domain.Exercises.ExerciseDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BodyPart")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClientOperationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasSetHistory")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LibraryImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("TrackingMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LibraryImageId");

                    b.HasIndex("Name", "Id");

                    b.HasIndex("OwnerId", "ClientOperationId")
                        .IsUnique()
                        .HasFilter("\"OwnerId\" IS NOT NULL AND \"ClientOperationId\" IS NOT NULL");

                    b.HasIndex("OwnerId", "IsArchived");

                    b.HasIndex("OwnerId", "NormalizedName")
                        .IsUnique()
                        .HasFilter("\"OwnerId\" IS NOT NULL AND NOT \"IsArchived\"");

                    b.ToTable("exercise_definitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercise_definitions_tracking_mode", "\"TrackingMode\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Exercises.ExerciseImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AnatomyApproved")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExerciseDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("MasterObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("MovementApproved")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewState")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RightsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("RightsReference")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ThumbnailObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseDefinitionId", "Version")
                        .IsUnique();

                    b.ToTable("exercise_images", (string)null);
                });

            modelBuilder.Entity("TrackZ.Domain.Exercises.ImageUploadTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CleanupClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CleanupClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CleanupProcessingLeaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("CleanupStagingObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("DeclaredContentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("DeclaredLength")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ExerciseDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExerciseImageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProcessingLeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StagingObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UploadLeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UploadLeaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseDefinitionId");

                    b.HasIndex("ExerciseImageId");

                    b.HasIndex("OwnerId", "Id");

                    b.ToTable("image_upload_tickets", null, t =>
                        {
                            t.HasCheckConstraint("CK_image_upload_tickets_processing_lease", "(\"State\" = 4 AND \"ProcessingStartedAt\" IS NOT NULL AND \"LeaseExpiresAt\" IS NOT NULL AND \"ProcessingLeaseId\" IS NOT NULL) OR (\"State\" <> 4 AND \"ProcessingStartedAt\" IS NULL AND \"LeaseExpiresAt\" IS NULL AND \"ProcessingLeaseId\" IS NULL)");

                            t.HasCheckConstraint("CK_image_upload_tickets_state", "\"State\" IN (1, 2, 3, 4, 5, 6, 7)");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "SessionId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TrackZ.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TrackZ.Domain.Progress.ExercisePerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AllTimeBestAssistedKg")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<int?>("AllTimeBestReps")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AllTimeBestWeightKg")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<Guid>("ExerciseDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("LastBestAssistedKg")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<int?>("LastBestReps")
                        .HasColumnType("integer");

                    b.Property<decimal?>("LastBestWeightKg")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<DateTimeOffset?>("LastPerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TrackingMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseDefinitionId");

                    b.HasIndex("UserId", "ExerciseDefinitionId")
                        .IsUnique();

                    b.ToTable("exercise_performances", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercise_performances_all_time_best_shape", "\"AllTimeBestReps\" IS NOT NULL AND \"AllTimeBestReps\" > 0 AND ((\"TrackingMode\" = 1 AND \"AllTimeBestWeightKg\" IS NOT NULL AND \"AllTimeBestWeightKg\" > 0 AND \"AllTimeBestAssistedKg\" IS NULL) OR (\"TrackingMode\" = 2 AND \"AllTimeBestWeightKg\" IS NULL AND \"AllTimeBestAssistedKg\" IS NULL) OR (\"TrackingMode\" = 3 AND \"AllTimeBestWeightKg\" IS NULL AND \"AllTimeBestAssistedKg\" IS NOT NULL AND \"AllTimeBestAssistedKg\" > 0))");

                            t.HasCheckConstraint("CK_exercise_performances_last_best_shape", "\"LastPerformedAt\" IS NOT NULL AND \"LastBestReps\" IS NOT NULL AND \"LastBestReps\" > 0 AND ((\"TrackingMode\" = 1 AND \"LastBestWeightKg\" IS NOT NULL AND \"LastBestWeightKg\" > 0 AND \"LastBestAssistedKg\" IS NULL) OR (\"TrackingMode\" = 2 AND \"LastBestWeightKg\" IS NULL AND \"LastBestAssistedKg\" IS NULL) OR (\"TrackingMode\" = 3 AND \"LastBestWeightKg\" IS NULL AND \"LastBestAssistedKg\" IS NOT NULL AND \"LastBestAssistedKg\" > 0))");

                            t.HasCheckConstraint("CK_exercise_performances_tracking_mode", "\"TrackingMode\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Workouts.SetEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("ActiveOrder")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasComputedColumnSql("CASE WHEN \"DeletedAt\" IS NULL THEN \"Order\" ELSE NULL END", true);

                    b.Property<decimal?>("AssistedKg")
                        .HasColumnType("numeric(8,3)");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("TrackingMode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric(8,3)");

                    b.Property<Guid>("WorkoutExerciseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId", "ActiveOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_set_entries_active_order");

                    b.HasIndex("WorkoutExerciseId", "TrackingMode");

                    b.ToTable("set_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_set_entries_mode_measurement", "(\"TrackingMode\" = 1 AND \"WeightKg\" > 0 AND \"AssistedKg\" IS NULL) OR (\"TrackingMode\" = 2 AND \"WeightKg\" IS NULL AND \"AssistedKg\" IS NULL) OR (\"TrackingMode\" = 3 AND \"WeightKg\" IS NULL AND \"AssistedKg\" > 0)");

                            t.HasCheckConstraint("CK_set_entries_order", "\"Order\" >= 0");

                            t.HasCheckConstraint("CK_set_entries_reps", "\"Reps\" BETWEEN 1 AND 999");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Workouts.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("ActiveOrder")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasComputedColumnSql("CASE WHEN \"DeletedAt\" IS NULL THEN \"Order\" ELSE NULL END", true);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExerciseDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("TrackingMode")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseDefinitionId", "WorkoutSessionId");

                    b.HasIndex("WorkoutSessionId", "ActiveOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_workout_exercises_active_order");

                    b.ToTable("workout_exercises", null, t =>
                        {
                            t.HasCheckConstraint("CK_workout_exercises_order", "\"Order\" >= 0");

                            t.HasCheckConstraint("CK_workout_exercises_tracking_mode", "\"TrackingMode\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Workouts.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "CompletedAt", "Id");

                    b.HasIndex("OwnerId", "Status", "DeletedAt");

                    b.ToTable("workout_sessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_workout_sessions_lifecycle", "(\"Status\" = 3 AND \"CompletedAt\" IS NOT NULL) OR (\"Status\" IN (1, 2) AND \"CompletedAt\" IS NULL)");

                            t.HasCheckConstraint("CK_workout_sessions_status", "\"Status\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Exercises.ExerciseDefinition", b =>
                {
                    b.HasOne("TrackZ.Domain.Exercises.ExerciseImage", null)
                        .WithMany()
                        .HasForeignKey("LibraryImageId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TrackZ.Domain.Exercises.ExerciseImage", b =>
                {
                    b.HasOne("TrackZ.Domain.Exercises.ExerciseDefinition", null)
                        .WithMany()
                        .HasForeignKey("ExerciseDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackZ.Domain.Exercises.ImageUploadTicket", b =>
                {
                    b.HasOne("TrackZ.Domain.Exercises.ExerciseDefinition", null)
                        .WithMany()
                        .HasForeignKey("ExerciseDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackZ.Domain.Exercises.ExerciseImage", null)
                        .WithMany()
                        .HasForeignKey("ExerciseImageId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TrackZ.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("TrackZ.Domain.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackZ.Domain.Progress.ExercisePerformance", b =>
                {
                    b.HasOne("TrackZ.Domain.Exercises.ExerciseDefinition", null)
                        .WithMany()
                        .HasForeignKey("ExerciseDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackZ.Domain.Workouts.SetEntry", b =>
                {
                    b.HasOne("TrackZ.Domain.Workouts.WorkoutExercise", null)
                        .WithMany("_sets")
                        .HasForeignKey("WorkoutExerciseId", "TrackingMode")
                        .HasPrincipalKey("Id", "TrackingMode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackZ.Domain.Workouts.WorkoutExercise", b =>
                {
                    b.HasOne("TrackZ.Domain.Exercises.ExerciseDefinition", null)
                        .WithMany()
                        .HasForeignKey("ExerciseDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrackZ.Domain.Workouts.WorkoutSession", null)
                        .WithMany("_exercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackZ.Domain.Workouts.WorkoutSession", b =>
                {
                    b.HasOne("TrackZ.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackZ.Domain.Identity.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("TrackZ.Domain.Workouts.WorkoutExercise", b =>
                {
                    b.Navigation("_sets");
                });

            modelBuilder.Entity("TrackZ.Domain.Workouts.WorkoutSession", b =>
                {
                    b.Navigation("_exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
