// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrackZ.Infrastructure.Persistence;

#nullable disable

namespace TrackZ.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828063250_AddPlateCountLoad")]
    partial class AddPlateCountLoad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrackZ.Domain.Exercises.ExerciseDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BodyPart")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClientOperationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasSetHistory")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LibraryImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("TrackingMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LibraryImageId");

                    b.HasIndex("Name", "Id");

                    b.HasIndex("OwnerId", "ClientOperationId")
                        .IsUnique()
                        .HasFilter("\"OwnerId\" IS NOT NULL AND \"ClientOperationId\" IS NOT NULL");

                    b.HasIndex("OwnerId", "IsArchived");

                    b.HasIndex("OwnerId", "NormalizedName")
                        .IsUnique()
                        .HasFilter("\"OwnerId\" IS NOT NULL AND NOT \"IsArchived\"");

                    b.ToTable("exercise_definitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercise_definitions_tracking_mode", "\"TrackingMode\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Exercises.ExerciseImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AnatomyApproved")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExerciseDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("MasterObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("MovementApproved")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewState")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RightsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("RightsReference")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ThumbnailObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseDefinitionId", "Version")
                        .IsUnique();

                    b.ToTable("exercise_images", (string)null);
                });

            modelBuilder.Entity("TrackZ.Domain.Exercises.ImageUploadTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CleanupClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CleanupClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CleanupProcessingLeaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("CleanupStagingObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("DeclaredContentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("DeclaredLength")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ExerciseDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExerciseImageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProcessingLeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StagingObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UploadLeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UploadLeaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseDefinitionId");

                    b.HasIndex("ExerciseImageId");

                    b.HasIndex("OwnerId", "Id");

                    b.ToTable("image_upload_tickets", null, t =>
                        {
                            t.HasCheckConstraint("CK_image_upload_tickets_processing_lease", "(\"State\" = 4 AND \"ProcessingStartedAt\" IS NOT NULL AND \"LeaseExpiresAt\" IS NOT NULL AND \"ProcessingLeaseId\" IS NOT NULL) OR (\"State\" <> 4 AND \"ProcessingStartedAt\" IS NULL AND \"LeaseExpiresAt\" IS NULL AND \"ProcessingLeaseId\" IS NULL)");

                            t.HasCheckConstraint("CK_image_upload_tickets_state", "\"State\" IN (1, 2, 3, 4, 5, 6, 7)");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Gamification.BadgeAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid>("BadgeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("BadgeKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BadgeDefinitionId");

                    b.HasIndex("UserId", "OccurredAt", "Id");

                    b.ToTable("badge_audit_events", null, t =>
                        {
                            t.HasCheckConstraint("CK_badge_audit_events_action", "\"Action\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Gamification.BadgeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Criteria")
                        .HasColumnType("integer");

                    b.Property<int>("CriteriaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("DescriptionResourceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameResourceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Threshold")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("badge_definitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_badge_definitions_criteria", "\"Criteria\" IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_badge_definitions_threshold", "\"Threshold\" >= 1");

                            t.HasCheckConstraint("CK_badge_definitions_version", "\"CriteriaVersion\" >= 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Criteria = 1,
                            CriteriaVersion = 1,
                            DescriptionResourceKey = "Badge_FirstWorkout_Description",
                            IconKey = "badge-first-workout",
                            Key = "first-workout",
                            NameResourceKey = "Badge_FirstWorkout_Name",
                            Threshold = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Criteria = 1,
                            CriteriaVersion = 1,
                            DescriptionResourceKey = "Badge_Workouts10_Description",
                            IconKey = "badge-workouts-10",
                            Key = "workouts-10",
                            NameResourceKey = "Badge_Workouts10_Name",
                            Threshold = 10
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Criteria = 1,
                            CriteriaVersion = 1,
                            DescriptionResourceKey = "Badge_Workouts25_Description",
                            IconKey = "badge-workouts-25",
                            Key = "workouts-25",
                            NameResourceKey = "Badge_Workouts25_Name",
                            Threshold = 25
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            Criteria = 1,
                            CriteriaVersion = 1,
                            DescriptionResourceKey = "Badge_Workouts50_Description",
                            IconKey = "badge-workouts-50",
                            Key = "workouts-50",
                            NameResourceKey = "Badge_Workouts50_Name",
                            Threshold = 50
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000005"),
                            Criteria = 2,
                            CriteriaVersion = 1,
                            DescriptionResourceKey = "Badge_Streak4_Description",
                            IconKey = "badge-streak-4",
                            Key = "streak-4",
                            NameResourceKey = "Badge_Streak4_Name",
                            Threshold = 4
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000006"),
                            Criteria = 2,
                            CriteriaVersion = 1,
                            DescriptionResourceKey = "Badge_Streak8_Description",
                            IconKey = "badge-streak-8",
                            Key = "streak-8",
                            NameResourceKey = "Badge_Streak8_Name",
                            Threshold = 8
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000007"),
                            Criteria = 2,
                            CriteriaVersion = 1,
                            DescriptionResourceKey = "Badge_Streak12_Description",
                            IconKey = "badge-streak-12",
                            Key = "streak-12",
                            NameResourceKey = "Badge_Streak12_Name",
                            Threshold = 12
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000008"),
                            Criteria = 3,
                            CriteriaVersion = 1,
                            DescriptionResourceKey = "Badge_Exercises10_Description",
                            IconKey = "badge-exercises-10",
                            Key = "exercises-10",
                            NameResourceKey = "Badge_Exercises10_Name",
                            Threshold = 10
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000009"),
                            Criteria = 3,
                            CriteriaVersion = 1,
                            DescriptionResourceKey = "Badge_Exercises25_Description",
                            IconKey = "badge-exercises-25",
                            Key = "exercises-25",
                            NameResourceKey = "Badge_Exercises25_Name",
                            Threshold = 25
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000010"),
                            Criteria = 4,
                            CriteriaVersion = 1,
                            DescriptionResourceKey = "Badge_FirstPr_Description",
                            IconKey = "badge-first-pr",
                            Key = "first-pr",
                            NameResourceKey = "Badge_FirstPr_Name",
                            Threshold = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000011"),
                            Criteria = 4,
                            CriteriaVersion = 1,
                            DescriptionResourceKey = "Badge_Prs10_Description",
                            IconKey = "badge-prs-10",
                            Key = "prs-10",
                            NameResourceKey = "Badge_Prs10_Name",
                            Threshold = 10
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Gamification.LevelThreshold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredXp")
                        .HasColumnType("integer");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RulesVersion", "Level")
                        .IsUnique();

                    b.HasIndex("RulesVersion", "RequiredXp")
                        .IsUnique();

                    b.ToTable("level_thresholds", null, t =>
                        {
                            t.HasCheckConstraint("CK_level_thresholds_level", "\"Level\" >= 1");

                            t.HasCheckConstraint("CK_level_thresholds_required_xp", "\"RequiredXp\" >= 0");

                            t.HasCheckConstraint("CK_level_thresholds_rules_version", "\"RulesVersion\" >= 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Level = 1,
                            RequiredXp = 0,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Level = 2,
                            RequiredXp = 250,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            Level = 3,
                            RequiredXp = 750,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            Level = 4,
                            RequiredXp = 1500,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            Level = 5,
                            RequiredXp = 2500,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000006"),
                            Level = 6,
                            RequiredXp = 3750,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000007"),
                            Level = 7,
                            RequiredXp = 5250,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000008"),
                            Level = 8,
                            RequiredXp = 7000,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000009"),
                            Level = 9,
                            RequiredXp = 9000,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000010"),
                            Level = 10,
                            RequiredXp = 11250,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000011"),
                            Level = 11,
                            RequiredXp = 13750,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000012"),
                            Level = 12,
                            RequiredXp = 16500,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000013"),
                            Level = 13,
                            RequiredXp = 19500,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000014"),
                            Level = 14,
                            RequiredXp = 22750,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000015"),
                            Level = 15,
                            RequiredXp = 26250,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000016"),
                            Level = 16,
                            RequiredXp = 30000,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000017"),
                            Level = 17,
                            RequiredXp = 34000,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000018"),
                            Level = 18,
                            RequiredXp = 38250,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000019"),
                            Level = 19,
                            RequiredXp = 42750,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000020"),
                            Level = 20,
                            RequiredXp = 47500,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000021"),
                            Level = 21,
                            RequiredXp = 52500,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000022"),
                            Level = 22,
                            RequiredXp = 57750,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000023"),
                            Level = 23,
                            RequiredXp = 63250,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000024"),
                            Level = 24,
                            RequiredXp = 69000,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000025"),
                            Level = 25,
                            RequiredXp = 75000,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000026"),
                            Level = 26,
                            RequiredXp = 81250,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000027"),
                            Level = 27,
                            RequiredXp = 87750,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000028"),
                            Level = 28,
                            RequiredXp = 94500,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000029"),
                            Level = 29,
                            RequiredXp = 101500,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000030"),
                            Level = 30,
                            RequiredXp = 108750,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000031"),
                            Level = 31,
                            RequiredXp = 116250,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000032"),
                            Level = 32,
                            RequiredXp = 124000,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000033"),
                            Level = 33,
                            RequiredXp = 132000,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000034"),
                            Level = 34,
                            RequiredXp = 140250,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000035"),
                            Level = 35,
                            RequiredXp = 148750,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000036"),
                            Level = 36,
                            RequiredXp = 157500,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000037"),
                            Level = 37,
                            RequiredXp = 166500,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000038"),
                            Level = 38,
                            RequiredXp = 175750,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000039"),
                            Level = 39,
                            RequiredXp = 185250,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000040"),
                            Level = 40,
                            RequiredXp = 195000,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000041"),
                            Level = 41,
                            RequiredXp = 205000,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000042"),
                            Level = 42,
                            RequiredXp = 215250,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000043"),
                            Level = 43,
                            RequiredXp = 225750,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000044"),
                            Level = 44,
                            RequiredXp = 236500,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000045"),
                            Level = 45,
                            RequiredXp = 247500,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000046"),
                            Level = 46,
                            RequiredXp = 258750,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000047"),
                            Level = 47,
                            RequiredXp = 270250,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000048"),
                            Level = 48,
                            RequiredXp = 282000,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000049"),
                            Level = 49,
                            RequiredXp = 294000,
                            RulesVersion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000050"),
                            Level = 50,
                            RequiredXp = 306250,
                            RulesVersion = 1
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Gamification.StreakState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BestWeeks")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentWeeks")
                        .HasColumnType("integer");

                    b.Property<int>("LastEvaluatedIsoWeek")
                        .HasColumnType("integer");

                    b.Property<int>("LastEvaluatedIsoYear")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("streak_states", null, t =>
                        {
                            t.HasCheckConstraint("CK_streak_states_best", "\"BestWeeks\" >= \"CurrentWeeks\"");

                            t.HasCheckConstraint("CK_streak_states_current", "\"CurrentWeeks\" >= 0");

                            t.HasCheckConstraint("CK_streak_states_iso_week", "\"LastEvaluatedIsoYear\" >= 1 AND \"LastEvaluatedIsoWeek\" BETWEEN 1 AND 53");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Gamification.UserBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("BadgeKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BadgeDefinitionId");

                    b.HasIndex("UserId", "BadgeDefinitionId")
                        .IsUnique();

                    b.ToTable("user_badges", (string)null);
                });

            modelBuilder.Entity("TrackZ.Domain.Gamification.UserProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("integer");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_progress", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_progress_level", "\"Level\" >= 1");

                            t.HasCheckConstraint("CK_user_progress_rules_version", "\"RulesVersion\" >= 1");

                            t.HasCheckConstraint("CK_user_progress_total_xp", "\"TotalXp\" >= 0");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Gamification.XpLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OriginId")
                        .HasColumnType("uuid");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OriginId", "CreatedAt");

                    b.HasIndex("UserId", "Reason", "SourceId")
                        .IsUnique();

                    b.ToTable("xp_ledger_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_xp_ledger_entries_amount", "\"Amount\" <> 0 AND (\"Reason\" = 4 OR \"Amount\" > 0)");

                            t.HasCheckConstraint("CK_xp_ledger_entries_reason", "\"Reason\" IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "SessionId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TrackZ.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("UTC");

                    b.Property<int>("WeeklyWorkoutGoal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_weekly_workout_goal", "\"WeeklyWorkoutGoal\" BETWEEN 1 AND 7");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Progress.ExercisePerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AllTimeBestAssistedKg")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<int?>("AllTimeBestPlateCount")
                        .HasColumnType("integer");

                    b.Property<int?>("AllTimeBestReps")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AllTimeBestWeightKg")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<Guid>("ExerciseDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("LastBestAssistedKg")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<int?>("LastBestPlateCount")
                        .HasColumnType("integer");

                    b.Property<int?>("LastBestReps")
                        .HasColumnType("integer");

                    b.Property<decimal?>("LastBestWeightKg")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<DateTimeOffset?>("LastPerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TrackingMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseDefinitionId");

                    b.HasIndex("UserId", "ExerciseDefinitionId")
                        .IsUnique();

                    b.ToTable("exercise_performances", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercise_performances_all_time_best_shape", "\"AllTimeBestReps\" > 0 AND ((\"TrackingMode\" = 1 AND \"AllTimeBestAssistedKg\" IS NULL AND ((\"AllTimeBestWeightKg\" > 0 AND \"AllTimeBestPlateCount\" IS NULL) OR (\"AllTimeBestWeightKg\" IS NULL AND \"AllTimeBestPlateCount\" > 0))) OR (\"TrackingMode\" = 2 AND \"AllTimeBestWeightKg\" IS NULL AND \"AllTimeBestAssistedKg\" IS NULL AND \"AllTimeBestPlateCount\" IS NULL) OR (\"TrackingMode\" = 3 AND \"AllTimeBestWeightKg\" IS NULL AND ((\"AllTimeBestAssistedKg\" > 0 AND \"AllTimeBestPlateCount\" IS NULL) OR (\"AllTimeBestAssistedKg\" IS NULL AND \"AllTimeBestPlateCount\" > 0))))");

                            t.HasCheckConstraint("CK_exercise_performances_last_best_shape", "\"LastPerformedAt\" IS NOT NULL AND \"LastBestReps\" > 0 AND ((\"TrackingMode\" = 1 AND \"LastBestAssistedKg\" IS NULL AND ((\"LastBestWeightKg\" > 0 AND \"LastBestPlateCount\" IS NULL) OR (\"LastBestWeightKg\" IS NULL AND \"LastBestPlateCount\" > 0))) OR (\"TrackingMode\" = 2 AND \"LastBestWeightKg\" IS NULL AND \"LastBestAssistedKg\" IS NULL AND \"LastBestPlateCount\" IS NULL) OR (\"TrackingMode\" = 3 AND \"LastBestWeightKg\" IS NULL AND ((\"LastBestAssistedKg\" > 0 AND \"LastBestPlateCount\" IS NULL) OR (\"LastBestAssistedKg\" IS NULL AND \"LastBestPlateCount\" > 0))))");

                            t.HasCheckConstraint("CK_exercise_performances_tracking_mode", "\"TrackingMode\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Sync.ProcessedClientOperation", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("UserId", "OperationId");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("processed_client_operations", null, t =>
                        {
                            t.HasCheckConstraint("CK_processed_client_operations_fingerprint", "length(\"RequestFingerprint\") = 64");

                            t.HasCheckConstraint("CK_processed_client_operations_result", "jsonb_typeof(\"ResultJson\") = 'object'");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Sync.SyncChange", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Sequence"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("ServerVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Sequence");

                    b.HasIndex("OwnerId", "OperationId")
                        .IsUnique();

                    b.HasIndex("OwnerId", "Sequence");

                    b.ToTable("sync_changes", null, t =>
                        {
                            t.HasCheckConstraint("CK_sync_changes_payload", "jsonb_typeof(\"PayloadJson\") = 'object'");

                            t.HasCheckConstraint("CK_sync_changes_sequence", "\"Sequence\" > 0");

                            t.HasCheckConstraint("CK_sync_changes_server_version", "\"ServerVersion\" >= 0");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Workouts.SetEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("ActiveOrder")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasComputedColumnSql("CASE WHEN \"DeletedAt\" IS NULL THEN \"Order\" ELSE NULL END", true);

                    b.Property<decimal?>("AssistedKg")
                        .HasColumnType("numeric(8,3)");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Effort")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("PlateCount")
                        .HasColumnType("integer");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("TrackingMode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric(8,3)");

                    b.Property<Guid>("WorkoutExerciseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId", "ActiveOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_set_entries_active_order");

                    b.HasIndex("WorkoutExerciseId", "TrackingMode");

                    b.ToTable("set_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_set_entries_effort", "\"Effort\" IS NULL OR \"Effort\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_set_entries_mode_measurement", "(\"TrackingMode\" = 1 AND \"AssistedKg\" IS NULL AND ((\"WeightKg\" > 0 AND \"PlateCount\" IS NULL) OR (\"WeightKg\" IS NULL AND \"PlateCount\" BETWEEN 1 AND 999))) OR (\"TrackingMode\" = 2 AND \"WeightKg\" IS NULL AND \"AssistedKg\" IS NULL AND \"PlateCount\" IS NULL) OR (\"TrackingMode\" = 3 AND \"WeightKg\" IS NULL AND ((\"AssistedKg\" > 0 AND \"PlateCount\" IS NULL) OR (\"AssistedKg\" IS NULL AND \"PlateCount\" BETWEEN 1 AND 999)))");

                            t.HasCheckConstraint("CK_set_entries_order", "\"Order\" >= 0");

                            t.HasCheckConstraint("CK_set_entries_reps", "\"Reps\" BETWEEN 1 AND 999");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Workouts.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("ActiveOrder")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasComputedColumnSql("CASE WHEN \"DeletedAt\" IS NULL THEN \"Order\" ELSE NULL END", true);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExerciseDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("TrackingMode")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseDefinitionId", "WorkoutSessionId");

                    b.HasIndex("WorkoutSessionId", "ActiveOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_workout_exercises_active_order");

                    b.ToTable("workout_exercises", null, t =>
                        {
                            t.HasCheckConstraint("CK_workout_exercises_order", "\"Order\" >= 0");

                            t.HasCheckConstraint("CK_workout_exercises_tracking_mode", "\"TrackingMode\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Workouts.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "CompletedAt", "Id");

                    b.HasIndex("OwnerId", "Status", "DeletedAt");

                    b.ToTable("workout_sessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_workout_sessions_lifecycle", "(\"Status\" = 3 AND \"CompletedAt\" IS NOT NULL) OR (\"Status\" IN (1, 2) AND \"CompletedAt\" IS NULL)");

                            t.HasCheckConstraint("CK_workout_sessions_status", "\"Status\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TrackZ.Domain.Exercises.ExerciseDefinition", b =>
                {
                    b.HasOne("TrackZ.Domain.Exercises.ExerciseImage", null)
                        .WithMany()
                        .HasForeignKey("LibraryImageId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TrackZ.Domain.Exercises.ExerciseImage", b =>
                {
                    b.HasOne("TrackZ.Domain.Exercises.ExerciseDefinition", null)
                        .WithMany()
                        .HasForeignKey("ExerciseDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackZ.Domain.Exercises.ImageUploadTicket", b =>
                {
                    b.HasOne("TrackZ.Domain.Exercises.ExerciseDefinition", null)
                        .WithMany()
                        .HasForeignKey("ExerciseDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackZ.Domain.Exercises.ExerciseImage", null)
                        .WithMany()
                        .HasForeignKey("ExerciseImageId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TrackZ.Domain.Gamification.BadgeAuditEvent", b =>
                {
                    b.HasOne("TrackZ.Domain.Gamification.BadgeDefinition", null)
                        .WithMany()
                        .HasForeignKey("BadgeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrackZ.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackZ.Domain.Gamification.StreakState", b =>
                {
                    b.HasOne("TrackZ.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackZ.Domain.Gamification.UserBadge", b =>
                {
                    b.HasOne("TrackZ.Domain.Gamification.BadgeDefinition", null)
                        .WithMany()
                        .HasForeignKey("BadgeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrackZ.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackZ.Domain.Gamification.UserProgress", b =>
                {
                    b.HasOne("TrackZ.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackZ.Domain.Gamification.XpLedgerEntry", b =>
                {
                    b.HasOne("TrackZ.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackZ.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("TrackZ.Domain.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackZ.Domain.Progress.ExercisePerformance", b =>
                {
                    b.HasOne("TrackZ.Domain.Exercises.ExerciseDefinition", null)
                        .WithMany()
                        .HasForeignKey("ExerciseDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackZ.Domain.Sync.ProcessedClientOperation", b =>
                {
                    b.HasOne("TrackZ.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackZ.Domain.Sync.SyncChange", b =>
                {
                    b.HasOne("TrackZ.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackZ.Domain.Workouts.SetEntry", b =>
                {
                    b.HasOne("TrackZ.Domain.Workouts.WorkoutExercise", null)
                        .WithMany("_sets")
                        .HasForeignKey("WorkoutExerciseId", "TrackingMode")
                        .HasPrincipalKey("Id", "TrackingMode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackZ.Domain.Workouts.WorkoutExercise", b =>
                {
                    b.HasOne("TrackZ.Domain.Exercises.ExerciseDefinition", null)
                        .WithMany()
                        .HasForeignKey("ExerciseDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrackZ.Domain.Workouts.WorkoutSession", null)
                        .WithMany("_exercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackZ.Domain.Workouts.WorkoutSession", b =>
                {
                    b.HasOne("TrackZ.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackZ.Domain.Identity.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("TrackZ.Domain.Workouts.WorkoutExercise", b =>
                {
                    b.Navigation("_sets");
                });

            modelBuilder.Entity("TrackZ.Domain.Workouts.WorkoutSession", b =>
                {
                    b.Navigation("_exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
