// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TrackZ.Infrastructure.Persistence;

#nullable disable

namespace TrackZ.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260815124500_EnforceExercisePerformanceTrackingMode")]
partial class EnforceExercisePerformanceTrackingMode
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(AppDbContext).Assembly);
    }
}
